version: "3.2"

services:
  api:
    build:
      context: .
    image: moleculer-proof
    container_name: moleculer-proof-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: moleculer-proof
    container_name: moleculer-proof-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
    networks:
      - internal

  helper:
    build:
      context: .
    image: moleculer-proof
    container_name: moleculer-proof-helper
    env_file: docker-compose.env
    environment:
      SERVICES: helper
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
    networks:
      - internal

  user:
    build:
      context: .
    image: moleculer-proof
    container_name: moleculer-poc-user
    env_file: docker-compose.env
    environment:
      SERVICES: user
    labels:
      - "traefik.enable=false"
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  traefik:
    image: traefik:1.7
    container_name: traefik
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - internal
      - default

networks:
  internal:
